"""add_training_tables

Revision ID: 1650d535ae8a
Revises: 75a9ed5f9600
Create Date: 2025-10-27 21:36:15.395128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1650d535ae8a'
down_revision: Union[str, Sequence[str], None] = '75a9ed5f9600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('total_iterations', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('budget_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('best_checkpoint_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name='check_training_job_status'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_training_jobs_agent', 'training_jobs', ['agent_id'], unique=False)
    op.create_index('idx_training_jobs_created', 'training_jobs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_training_jobs_status', 'training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_training_jobs_agent_id'), 'training_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_created_at'), 'training_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_jobs_job_id'), 'training_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    op.create_table('policy_checkpoints',
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('policy_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_s3_path', sa.String(length=500), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index('idx_policy_checkpoints_agent', 'policy_checkpoints', ['agent_id'], unique=False)
    op.create_index('idx_policy_checkpoints_created', 'policy_checkpoints', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_policy_checkpoints_job', 'policy_checkpoints', ['job_id'], unique=False)
    op.create_index('idx_policy_checkpoints_validation', 'policy_checkpoints', ['validation_score'], unique=False)
    op.create_index(op.f('ix_policy_checkpoints_agent_id'), 'policy_checkpoints', ['agent_id'], unique=False)
    op.create_index(op.f('ix_policy_checkpoints_checkpoint_id'), 'policy_checkpoints', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_policy_checkpoints_created_at'), 'policy_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_checkpoints_job_id'), 'policy_checkpoints', ['job_id'], unique=False)
    op.create_table('trajectories',
    sa.Column('trajectory_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('normalized_reward', sa.Float(), nullable=True),
    sa.Column('advantage', sa.Float(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trajectory_id')
    )
    op.create_index('idx_trajectories_agent', 'trajectories', ['agent_id'], unique=False)
    op.create_index('idx_trajectories_created', 'trajectories', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_trajectories_job', 'trajectories', ['job_id'], unique=False)
    op.create_index('idx_trajectories_steps_gin', 'trajectories', ['steps'], unique=False, postgresql_using='gin')
    op.create_index('idx_trajectories_success', 'trajectories', ['success'], unique=False)
    op.create_index(op.f('ix_trajectories_agent_id'), 'trajectories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trajectories_created_at'), 'trajectories', ['created_at'], unique=False)
    op.create_index(op.f('ix_trajectories_job_id'), 'trajectories', ['job_id'], unique=False)
    op.create_index(op.f('ix_trajectories_success'), 'trajectories', ['success'], unique=False)
    op.create_index(op.f('ix_trajectories_trajectory_id'), 'trajectories', ['trajectory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trajectories_trajectory_id'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_success'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_job_id'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_created_at'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_agent_id'), table_name='trajectories')
    op.drop_index('idx_trajectories_success', table_name='trajectories')
    op.drop_index('idx_trajectories_steps_gin', table_name='trajectories', postgresql_using='gin')
    op.drop_index('idx_trajectories_job', table_name='trajectories')
    op.drop_index('idx_trajectories_created', table_name='trajectories', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_trajectories_agent', table_name='trajectories')
    op.drop_table('trajectories')
    op.drop_index(op.f('ix_policy_checkpoints_job_id'), table_name='policy_checkpoints')
    op.drop_index(op.f('ix_policy_checkpoints_created_at'), table_name='policy_checkpoints')
    op.drop_index(op.f('ix_policy_checkpoints_checkpoint_id'), table_name='policy_checkpoints')
    op.drop_index(op.f('ix_policy_checkpoints_agent_id'), table_name='policy_checkpoints')
    op.drop_index('idx_policy_checkpoints_validation', table_name='policy_checkpoints')
    op.drop_index('idx_policy_checkpoints_job', table_name='policy_checkpoints')
    op.drop_index('idx_policy_checkpoints_created', table_name='policy_checkpoints', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_policy_checkpoints_agent', table_name='policy_checkpoints')
    op.drop_table('policy_checkpoints')
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_job_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_created_at'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_agent_id'), table_name='training_jobs')
    op.drop_index('idx_training_jobs_status', table_name='training_jobs')
    op.drop_index('idx_training_jobs_created', table_name='training_jobs', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_training_jobs_agent', table_name='training_jobs')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###
