"""add_tool_execution_history_table

Revision ID: 83591e23ca42
Revises: 1650d535ae8a
Create Date: 2025-11-01 21:40:26.475045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83591e23ca42'
down_revision: Union[str, Sequence[str], None] = '1650d535ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('tool_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'timeout', 'cancelled', name='toolexecutionstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('execution_context', sa.JSON(), nullable=False),
    sa.Column('execution_metadata', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_execution_agent_tool', 'tool_executions', ['agent_id', 'tool_id'], unique=False)
    op.create_index('idx_tool_execution_status_time', 'tool_executions', ['status', 'timestamp'], unique=False)
    op.create_index('idx_tool_execution_timestamp', 'tool_executions', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_tool_execution_tool_time', 'tool_executions', ['tool_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_tool_executions_agent_id'), 'tool_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_request_id'), 'tool_executions', ['request_id'], unique=True)
    op.create_index(op.f('ix_tool_executions_status'), 'tool_executions', ['status'], unique=False)
    op.create_index(op.f('ix_tool_executions_timestamp'), 'tool_executions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_id'), 'tool_executions', ['tool_id'], unique=False)
    op.drop_index(op.f('idx_agent_capability_embedding'), table_name='agents', postgresql_ops={'capability_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_message_queue_priority'), 'message_queue', ['priority'], unique=False)
    op.drop_index(op.f('idx_policy_checkpoints_created'), table_name='policy_checkpoints')
    op.create_index('idx_policy_checkpoints_created', 'policy_checkpoints', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_session_created_at'), table_name='session_snapshots')
    op.create_index('idx_session_created_at', 'session_snapshots', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # Convert tags from JSON to JSONB to support GIN index
    op.alter_column('session_snapshots', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index('idx_session_tags', 'session_snapshots', ['tags'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('idx_training_jobs_created'), table_name='training_jobs')
    op.create_index('idx_training_jobs_created', 'training_jobs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_trajectories_created'), table_name='trajectories')
    op.create_index('idx_trajectories_created', 'trajectories', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trajectories_created', table_name='trajectories', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_trajectories_created'), 'trajectories', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_training_jobs_created', table_name='training_jobs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_training_jobs_created'), 'training_jobs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_session_tags', table_name='session_snapshots', postgresql_using='gin')
    # Revert tags from JSONB back to JSON
    op.alter_column('session_snapshots', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('idx_session_created_at', table_name='session_snapshots', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_session_created_at'), 'session_snapshots', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_policy_checkpoints_created', table_name='policy_checkpoints', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_policy_checkpoints_created'), 'policy_checkpoints', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_message_queue_priority'), table_name='message_queue')
    op.create_index(op.f('idx_agent_capability_embedding'), 'agents', ['capability_embedding'], unique=False, postgresql_ops={'capability_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_tool_executions_tool_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_timestamp'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_status'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_request_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_agent_id'), table_name='tool_executions')
    op.drop_index('idx_tool_execution_tool_time', table_name='tool_executions')
    op.drop_index('idx_tool_execution_timestamp', table_name='tool_executions', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_tool_execution_status_time', table_name='tool_executions')
    op.drop_index('idx_tool_execution_agent_tool', table_name='tool_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###
