"""
CQRS Module

Command Query Responsibility Segregation for orchestration layer.

Provides:
- Command models and handlers for write operations
- Query models and handlers for read operations
- Event sourcing for complete audit trails
- Read models optimized for query performance
- Projections for eventual consistency
"""

from .commands import (
    AssignAgentCommand,
    CancelTaskCommand,
    CancelWorkflowCommand,
    Command,
    CommandBus,
    CommandHandler,
    CommandResult,
    CommandType,
    CreateWorkflowCommand,
    DeleteWorkflowCommand,
    PauseWorkflowCommand,
    ReplaceAgentCommand,
    ResumeWorkflowCommand,
    RetryTaskCommand,
    ScheduleTaskCommand,
    StartWorkflowCommand,
    UnassignAgentCommand,
    UpdateWorkflowCommand,
)
from .event_store import (
    ConcurrencyError,
    EventRecord,
    EventStore,
    EventStreamResult,
    PostgreSQLEventStore,
    SnapshotData,
    SnapshotRecord,
)
from .events import (
    AgentAssignedEvent,
    AgentReplacedEvent,
    AgentUnassignedEvent,
    DomainEvent,
    EventType,
    StateSnapshotCreatedEvent,
    TaskCompletedEvent,
    TaskFailedEvent,
    TaskRetriedEvent,
    TaskScheduledEvent,
    TaskStartedEvent,
    WorkflowCancelledEvent,
    WorkflowCompletedEvent,
    WorkflowCreatedEvent,
    WorkflowFailedEvent,
    WorkflowPausedEvent,
    WorkflowResumedEvent,
    WorkflowStartedEvent,
    WorkflowUpdatedEvent,
    deserialize_event,
)
from .projections import (
    AgentAssignmentProjection,
    ExecutionProjection,
    Projection,
    ProjectionManager,
    TaskProjection,
    WorkflowProjection,
)
from .queries import (
    GetAgentAssignmentsQuery,
    GetExecutionMetricsQuery,
    GetExecutionQuery,
    GetTaskQuery,
    GetTaskStatusQuery,
    GetWorkflowHistoryQuery,
    GetWorkflowQuery,
    GetWorkflowStatusQuery,
    ListAgentsInWorkflowQuery,
    ListExecutionsQuery,
    ListTasksQuery,
    ListWorkflowsQuery,
    Query,
    QueryBus,
    QueryHandler,
    QueryResult,
    QueryType,
)
from .read_models import (
    AgentAssignmentReadModel,
    ExecutionReadModel,
    TaskReadModel,
    WorkflowMetricsReadModel,
    WorkflowReadModel,
)

__all__ = [
    # Commands
    "Command",
    "CommandType",
    "CommandHandler",
    "CommandBus",
    "CommandResult",
    "CreateWorkflowCommand",
    "UpdateWorkflowCommand",
    "DeleteWorkflowCommand",
    "StartWorkflowCommand",
    "PauseWorkflowCommand",
    "ResumeWorkflowCommand",
    "CancelWorkflowCommand",
    "AssignAgentCommand",
    "UnassignAgentCommand",
    "ReplaceAgentCommand",
    "ScheduleTaskCommand",
    "RetryTaskCommand",
    "CancelTaskCommand",
    # Events
    "DomainEvent",
    "EventType",
    "WorkflowCreatedEvent",
    "WorkflowUpdatedEvent",
    "WorkflowStartedEvent",
    "WorkflowPausedEvent",
    "WorkflowResumedEvent",
    "WorkflowCompletedEvent",
    "WorkflowFailedEvent",
    "WorkflowCancelledEvent",
    "AgentAssignedEvent",
    "AgentUnassignedEvent",
    "AgentReplacedEvent",
    "TaskScheduledEvent",
    "TaskStartedEvent",
    "TaskCompletedEvent",
    "TaskFailedEvent",
    "TaskRetriedEvent",
    "StateSnapshotCreatedEvent",
    "deserialize_event",
    # Event Store
    "EventStore",
    "PostgreSQLEventStore",
    "EventRecord",
    "SnapshotRecord",
    "EventStreamResult",
    "SnapshotData",
    "ConcurrencyError",
    # Queries
    "Query",
    "QueryType",
    "QueryHandler",
    "QueryBus",
    "QueryResult",
    "GetWorkflowQuery",
    "ListWorkflowsQuery",
    "GetWorkflowStatusQuery",
    "GetWorkflowHistoryQuery",
    "GetAgentAssignmentsQuery",
    "ListAgentsInWorkflowQuery",
    "GetTaskQuery",
    "ListTasksQuery",
    "GetTaskStatusQuery",
    "GetExecutionQuery",
    "ListExecutionsQuery",
    "GetExecutionMetricsQuery",
    # Read Models
    "WorkflowReadModel",
    "ExecutionReadModel",
    "AgentAssignmentReadModel",
    "TaskReadModel",
    "WorkflowMetricsReadModel",
    # Projections
    "Projection",
    "ProjectionManager",
    "WorkflowProjection",
    "ExecutionProjection",
    "AgentAssignmentProjection",
    "TaskProjection",
]
